ci: Disable `codecov` PR issue comments (#12030)
Signed-off-by: oliver könig <okoenig@nvidia.com>
Signed-off-by: Youngeun Kwon <youngeunk@nvidia.com>

diff --git a/.github/workflows/_test_template.yml b/.github/workflows/_test_template.yml
--- a/.github/workflows/_test_template.yml
+++ b/.github/workflows/_test_template.yml
@@ -20,7 +20,7 @@ on:
         type: string
         description: Script to run after main test
         required: false
-        default: ":"
+        default: ':'
       IS_OPTIONAL:
         type: boolean
         description: Failure will cancel all other tests if set to true
@@ -37,7 +37,7 @@ on:
         value: ${{ jobs.main.outputs.conclusion }}
       log:
         description: Last 2000 characters of the test step's log
-        value: ${{ jobs.main.outputs.log }} 
+        value: ${{ jobs.main.outputs.log }}
       potential_infra_failure:
         description: Boolean flag when infra-related keyword spotted in logs.
         value: ${{ jobs.main.outputs.potential_infra_failure }}
@@ -45,142 +45,147 @@ on:
         description: Key of coverage_report artifact
         value: ${{ jobs.main.outputs.coverage_report }}
 jobs:
-  
   main:
-    runs-on: ${{ inputs.RUNNER }} 
+    runs-on: ${{ inputs.RUNNER }}
     outputs:
-      conclusion: ${{ steps.main.conclusion }}
-      log: ${{ steps.main.outputs.log }}
-      potential_infra_failure: ${{ steps.main.outputs.potential_infra_failure }}
-      coverage_report: ${{ steps.main.outputs.coverage_report }}
+      conclusion: ${{ steps.check.conclusion }}
+      log: ${{ steps.check.outputs.log }}
+      potential_infra_failure: ${{ steps.check.outputs.potential_infra_failure }}
+      coverage_report: ${{ steps.check.outputs.coverage_report }}
     env:
       DIR: ${{ github.run_id }}
     steps:
-        - name: Docker system cleanup
-          run: |
-            docker system prune -af --filter "until=24h" --force || true
+      - name: Docker system cleanup
+        run: |
+          docker system prune -af --filter "until=24h" --force || true
 
-        - name: Docker pull image
-          run: |
-            docker pull nemoci.azurecr.io/nemo_container:${{ github.run_id }}
+      - name: Docker pull image
+        run: |
+          docker pull nemoci.azurecr.io/nemo_container:${{ github.run_id }}
 
-        - name: Start container
-          env:
-            DIR: ${{ github.run_id }}
-          run: |
-            mkdir -p $DIR
+      - name: Start container
+        env:
+          DIR: ${{ github.run_id }}
+        run: |
+          mkdir -p $DIR
 
-            ARG=("")
-            if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
-              ARG=("--runtime=nvidia --gpus all")
-            fi
+          ARG=("")
+          if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
+            ARG=("--runtime=nvidia --gpus all")
+          fi
 
-            cmd=$(cat <<RUN_TEST_EOF
-            #!/bin/bash
-            docker container rm -f nemo_container_${{ github.run_id }} || true
-            docker run \
-              --rm \
-              -d \
-              --name nemo_container_${{ github.run_id }} ${ARG[@]} \
-              --shm-size=64g \
-              --env TRANSFORMERS_OFFLINE=0 \
-              --env HYDRA_FULL_ERROR=1 \
-              --env HF_HOME=/home/TestData/HF_HOME \
-              --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
-              bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
-            RUN_TEST_EOF
-            )
+          cmd=$(cat <<RUN_TEST_EOF
+          #!/bin/bash
+          docker container rm -f nemo_container_${{ github.run_id }} || true
+          docker run \
+            --rm \
+            -d \
+            --name nemo_container_${{ github.run_id }} ${ARG[@]} \
+            --shm-size=64g \
+            --env TRANSFORMERS_OFFLINE=0 \
+            --env HYDRA_FULL_ERROR=1 \
+            --env HF_HOME=/home/TestData/HF_HOME \
+            --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
+            bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
+          RUN_TEST_EOF
+          )
+
+          echo "$cmd" | tee "$DIR/retry_job.sh"
+          bash $DIR/retry_job.sh
+
+      - name: Create run-script
+        env:
+          DIR: ${{ github.run_id }}
+          SCRIPT: ${{ inputs.SCRIPT }}
+        id: create
+        run: |
+          SCRIPT=$(echo "$SCRIPT" | grep -v '^#')
+          SCRIPT=$(perl -pe 'chomp if eof' <<< "$SCRIPT")
+
+          mkdir -p $DIR
+          rm $DIR/.coverage || true
+          rm $DIR/err.log || true
+
+          cmd=$(cat <<RUN_TEST_EOF
+          #!/bin/bash
             
-            echo "$cmd" | tee "$DIR/retry_job.sh"
-            bash $DIR/retry_job.sh
-        
-        - name: Create run-script
-          env:
-            DIR: ${{ github.run_id }}
-            SCRIPT: ${{ inputs.SCRIPT }}
-          id: create
-          run: |
-            SCRIPT=$(echo "$SCRIPT" | grep -v '^#')
-            SCRIPT=$(perl -pe 'chomp if eof' <<< "$SCRIPT")
-            
-            mkdir -p $DIR
-            rm $DIR/.coverage || true
-            rm $DIR/err.log || true
+          (
+            set -e
 
-            cmd=$(cat <<RUN_TEST_EOF
-            #!/bin/bash
-              
-            (
-              set -e
+            docker exec nemo_container_${{ github.run_id }} bash -c '$SCRIPT && echo "Finished successfully." || echo "Did not finish."'
+          ) 2>&1 | tee $DIR/err.log
 
-              docker exec nemo_container_${{ github.run_id }} bash -c '$SCRIPT && echo "Finished successfully." || echo "Did not finish."'
-            ) 2>&1 | tee $DIR/err.log
+          RUN_TEST_EOF
+          )
 
-            RUN_TEST_EOF
-            )
+          echo "timeout_in_seconds=$(( ${{ inputs.TIMEOUT }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
+          echo "$cmd" | tee "$DIR/job.sh"
 
-            echo "timeout_in_seconds=$(( ${{ inputs.TIMEOUT }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
-            echo "$cmd" | tee "$DIR/job.sh"
+      - name: Run main script
+        uses: nick-fields/retry@v3
+        with:
+          timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
+          max_attempts: 3
+          shell: bash
+          retry_on: timeout
+          command: /bin/bash ${{ github.run_id }}/job.sh
+          on_retry_command: /bin/bash ${{ github.run_id }}/retry_job.sh
 
-        - name: Run main script
-          uses: nick-fields/retry@v3
-          with:
-            timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
-            max_attempts: 3
-            shell: bash
-            retry_on: timeout
-            command: /bin/bash ${{ github.run_id }}/job.sh 
-            on_retry_command: /bin/bash ${{ github.run_id }}/retry_job.sh 
-        
-        - name: Check result
-          id: check
-          env:
-            SAVE_COVERAGE_REPORT: ${{ inputs.SAVE_COVERAGE_REPORT }}
-          run: |
-            cat $DIR/err.log
-            
-            log=$(tail -c 2000 $DIR/err.log |  base64 -w 0)
-            echo "log=$log" >> "$GITHUB_OUTPUT"
+      - name: Check result
+        id: check
+        env:
+          SAVE_COVERAGE_REPORT: ${{ inputs.SAVE_COVERAGE_REPORT }}
+          IS_OPTIONAL: ${{ inputs.IS_OPTIONAL }}
+        run: |
+          cat $DIR/err.log
 
-            potential_infra_failure=$(cat $DIR/err.log | grep -Eqiw "device" && echo true || echo false)
-            echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"
+          log=$(tail -c 2000 $DIR/err.log |  base64 -w 0)
+          echo "log=$log" >> "$GITHUB_OUTPUT"
 
-            coverage_report=coverage-${{ github.run_id }}-$(uuidgen)
-            echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
+          potential_infra_failure=$(cat $DIR/err.log | grep -Eqiw "device" && echo true || echo false)
+          echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"
 
-            if [[ "$SAVE_COVERAGE_REPORT" == "true" ]]; then
-              docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage $DIR/.coverage 
-              docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml $DIR/coverage.xml
+          coverage_report=coverage-${{ github.run_id }}-$(uuidgen)
+          echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
 
-            fi
+          if [[ "$SAVE_COVERAGE_REPORT" == "true" ]]; then
+            docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage $DIR/.coverage 
+            docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml $DIR/coverage.xml
 
-            IS_SUCCESS=$(tail -n 1 $DIR/err.log | grep -q "Finished successfully." && echo "true" || echo "false")
+          fi
 
-            if [[ "$IS_SUCCESS" == "false" ]]; then
-              echo Test did not finish successfully.
-              exit 1
-            fi
+          IS_SUCCESS=$(tail -n 1 $DIR/err.log | grep -q "Finished successfully." && echo "true" || echo "false")
 
-            exit $EXIT_CODE
+          if [[ "$IS_SUCCESS" == "false" && "$IS_OPTIONAL" == "true" ]]; then
+            echo "::warning:: Test failed, but displayed as successful because it is marked as optional."
+            IS_SUCCESS=true
+          fi
 
-        - name: Upload artifacts
-          uses: actions/upload-artifact@v4
-          if: inputs.SAVE_COVERAGE_REPORT == true
-          with:
-            name: ${{ steps.check.outputs.coverage_report }}
-            path: |
-              ${{ github.run_id }}/coverage.xml
-              ${{ github.run_id }}/.coverage
-            include-hidden-files: true
+          if [[ "$IS_SUCCESS" == "false" ]]; then
+            echo Test did not finish successfully.
+            exit 1
+          fi
 
-        - uses: "NVIDIA/NeMo/.github/actions/cancel-workflow@main"
-          if: failure() && inputs.IS_OPTIONAL == false && !contains(github.event.pull_request.labels.*.name, 'no-fail-fast')
-        - name: after_script
-          if: always() && inputs.AFTER_SCRIPT != ':'
-          run: |
-            docker exec nemo_container_${{ github.run_id }} bash -c '${{ inputs.AFTER_SCRIPT }}'
+          exit $EXIT_CODE
 
-        - name: Container shutdown
-          if: always()
-          run: |
-            docker container rm -f nemo_container_${{ github.run_id }} || true
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        if: inputs.SAVE_COVERAGE_REPORT == true
+        with:
+          name: ${{ steps.check.outputs.coverage_report }}
+          path: |
+            ${{ github.run_id }}/coverage.xml
+            ${{ github.run_id }}/.coverage
+          include-hidden-files: true
+
+      - uses: 'NVIDIA/NeMo/.github/actions/cancel-workflow@main'
+        if: failure() && inputs.IS_OPTIONAL == false && !contains(github.event.pull_request.labels.*.name, 'no-fail-fast')
+      - name: after_script
+        if: always() && inputs.AFTER_SCRIPT != ':'
+        run: |
+          docker exec nemo_container_${{ github.run_id }} bash -c '${{ inputs.AFTER_SCRIPT }}'
+
+      - name: Container shutdown
+        if: always()
+        run: |
+          docker container rm -f nemo_container_${{ github.run_id }} || true
