test
Signed-off-by: oliver könig <okoenig@nvidia.com>

diff --git a/.github/workflows/_test_template.yml b/.github/workflows/_test_template.yml
--- a/.github/workflows/_test_template.yml
+++ b/.github/workflows/_test_template.yml
@@ -43,7 +43,7 @@ on:
         value: ${{ jobs.main.outputs.potential_infra_failure }}
 jobs:
   main:
-    runs-on: ${{ inputs.RUNNER }}
+    runs-on: ubuntu-latest # ${{ inputs.RUNNER }}
     name: ${{ inputs.SCRIPT }}
     outputs:
       conclusion: ${{ steps.check.conclusion }}
@@ -55,134 +55,137 @@ jobs:
       SCRIPT: ${{ inputs.SCRIPT }}
       IS_UNIT_TEST: ${{ inputs.IS_UNIT_TEST }}
     steps:
-      - name: Docker system cleanup
-        run: |
-          docker system prune -af --filter "until=24h" --force || true
+      - name: Dummy
+        run: echo Pass
 
-      - name: Docker pull image
-        run: |
-          docker pull nemoci.azurecr.io/nemo_container:${{ github.run_id }}
+      # - name: Docker system cleanup
+      #   run: |
+      #     docker system prune -af --filter "until=24h" --force || true
 
-      - name: Start container
-        run: |
-          mkdir -p $DIR
+      # - name: Docker pull image
+      #   run: |
+      #     docker pull nemoci.azurecr.io/nemo_container:${{ github.run_id }}
 
-          ARG=("")
-          if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
-            ARG=("--runtime=nvidia --gpus all")
-          fi
+      # - name: Start container
+      #   run: |
+      #     mkdir -p $DIR
 
-          cmd=$(cat <<RUN_TEST_EOF
-          #!/bin/bash
-          docker container rm -f nemo_container_${{ github.run_id }} || true
-          docker run \
-            --rm \
-            -d \
-            --name nemo_container_${{ github.run_id }} ${ARG[@]} \
-            --shm-size=64g \
-            --env TRANSFORMERS_OFFLINE=0 \
-            --env HYDRA_FULL_ERROR=1 \
-            --env HF_HOME=/home/TestData/HF_HOME \
-            --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
-            bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
-          RUN_TEST_EOF
-          )
+      #     ARG=("")
+      #     if [[ "${{ inputs.RUNNER }}" != *cpu* ]]; then
+      #       ARG=("--runtime=nvidia --gpus all")
+      #     fi
 
-          echo "$cmd" | tee "$DIR/retry_job.sh"
-          bash $DIR/retry_job.sh
+      #     cmd=$(cat <<RUN_TEST_EOF
+      #     #!/bin/bash
+      #     docker container rm -f nemo_container_${{ github.run_id }} || true
+      #     docker run \
+      #       --rm \
+      #       -d \
+      #       --name nemo_container_${{ github.run_id }} ${ARG[@]} \
+      #       --shm-size=64g \
+      #       --env TRANSFORMERS_OFFLINE=0 \
+      #       --env HYDRA_FULL_ERROR=1 \
+      #       --env HF_HOME=/home/TestData/HF_HOME \
+      #       --volume /mnt/datadrive/TestData:/home/TestData nemoci.azurecr.io/nemo_container:${{ github.run_id }} \
+      #       bash -c "sleep $(( ${{ inputs.TIMEOUT }} * 60 + 60 ))"
+      #     RUN_TEST_EOF
+      #     )
 
-      - name: Create run-script
-        id: create
-        run: |
+      #     echo "$cmd" | tee "$DIR/retry_job.sh"
+      #     bash $DIR/retry_job.sh
 
-          COVERAGE_PREFIX=$([[ "$IS_UNIT_TEST" == "true" ]] && echo "unit-test" || echo "e2e")
-          echo "coverage-prefix=$COVERAGE_PREFIX" | tee -a "$GITHUB_OUTPUT"
+      # - name: Create run-script
+      #   id: create
+      #   run: |
 
-          mkdir -p $DIR
-          rm $DIR/.coverage || true
-          rm $DIR/err.log || true
+      #     COVERAGE_PREFIX=$([[ "$IS_UNIT_TEST" == "true" ]] && echo "unit-test" || echo "e2e")
+      #     echo "coverage-prefix=$COVERAGE_PREFIX" | tee -a "$GITHUB_OUTPUT"
 
-          cmd=$(cat <<RUN_TEST_EOF
-          #!/bin/bash
-            
-          (
-            set -e
+      #     mkdir -p $DIR
+      #     rm $DIR/.coverage || true
+      #     rm $DIR/err.log || true
 
-            docker exec -t nemo_container_${{ github.run_id }} bash -c 'RUN_ID=${{ github.run_id }} bash tests/functional_tests/$SCRIPT.sh && echo "Finished successfully." || echo "Did not finish."'
-          ) 2>&1 | tee $DIR/err.log
+      #     cmd=$(cat <<RUN_TEST_EOF
+      #     #!/bin/bash
 
-          RUN_TEST_EOF
-          )
+      #     (
+      #       set -e
 
-          echo "timeout_in_seconds=$(( ${{ inputs.TIMEOUT }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
-          echo "$cmd" | tee "$DIR/job.sh"
+      #       docker exec -t nemo_container_${{ github.run_id }} bash -c 'RUN_ID=${{ github.run_id }} bash tests/functional_tests/$SCRIPT.sh && echo "Finished successfully." || echo "Did not finish."'
+      #     ) 2>&1 | tee $DIR/err.log
 
-      - name: Run main script
-        uses: nick-fields/retry@v3
-        with:
-          timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
-          max_attempts: 3
-          shell: bash
-          retry_on: timeout
-          command: /bin/bash ${{ github.run_id }}/job.sh
-          on_retry_command: /bin/bash ${{ github.run_id }}/retry_job.sh
+      #     RUN_TEST_EOF
+      #     )
 
-      - name: Check result
-        id: check
-        run: |
-          cat $DIR/err.log
+      #     echo "timeout_in_seconds=$(( ${{ inputs.TIMEOUT }} * 60 ))" | tee -a "$GITHUB_OUTPUT"
+      #     echo "$cmd" | tee "$DIR/job.sh"
 
-          log=$(tail -c 2000 $DIR/err.log |  base64 -w 0)
-          echo "log=$log" >> "$GITHUB_OUTPUT"
+      # - name: Run main script
+      #   uses: nick-fields/retry@v3
+      #   with:
+      #     timeout_seconds: ${{ steps.create.outputs.timeout_in_seconds }}
+      #     max_attempts: 3
+      #     shell: bash
+      #     retry_on: timeout
+      #     command: /bin/bash ${{ github.run_id }}/job.sh
+      #     on_retry_command: /bin/bash ${{ github.run_id }}/retry_job.sh
 
-          potential_infra_failure=$(cat $DIR/err.log | grep -Eqiw "device" && echo true || echo false)
-          echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"
+      # - name: Check result
+      #   id: check
+      #   run: |
+      #     cat $DIR/err.log
 
-          docker exec nemo_container_${{ github.run_id }} coverage combine
-          docker exec nemo_container_${{ github.run_id }} coverage xml
-          docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage $DIR/.coverage 
-          docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml $DIR/coverage.xml
+      #     log=$(tail -c 2000 $DIR/err.log |  base64 -w 0)
+      #     echo "log=$log" >> "$GITHUB_OUTPUT"
 
-          coverage_report=coverage-${{ steps.create.outputs.coverage-prefix }}-${{ github.run_id }}-$(uuidgen)
-          echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
+      #     potential_infra_failure=$(cat $DIR/err.log | grep -Eqiw "device" && echo true || echo false)
+      #     echo "potential_infra_failure=$potential_infra_failure" >> "$GITHUB_OUTPUT"
 
-          IS_SUCCESS=$(tail -n 1 $DIR/err.log | grep -q "Finished successfully." && echo "true" || echo "false")
+      #     docker exec nemo_container_${{ github.run_id }} coverage combine
+      #     docker exec nemo_container_${{ github.run_id }} coverage xml
+      #     docker cp nemo_container_${{ github.run_id }}:/workspace/.coverage $DIR/.coverage
+      #     docker cp nemo_container_${{ github.run_id }}:/workspace/coverage.xml $DIR/coverage.xml
 
-          if [[ "$IS_SUCCESS" == "false" && "$IS_OPTIONAL" == "true" ]]; then
-            echo "::warning:: Test failed, but displayed as successful because it is marked as optional."
-            IS_SUCCESS=true
-          fi
+      #     coverage_report=coverage-${{ steps.create.outputs.coverage-prefix }}-${{ github.run_id }}-$(uuidgen)
+      #     echo "coverage_report=$coverage_report" >> "$GITHUB_OUTPUT"
 
-          if [[ "$IS_SUCCESS" == "false" ]]; then
-            echo Test did not finish successfully.
-            exit 1
-          fi
+      #     IS_SUCCESS=$(tail -n 1 $DIR/err.log | grep -q "Finished successfully." && echo "true" || echo "false")
 
-          exit $EXIT_CODE
+      #     if [[ "$IS_SUCCESS" == "false" && "$IS_OPTIONAL" == "true" ]]; then
+      #       echo "::warning:: Test failed, but displayed as successful because it is marked as optional."
+      #       IS_SUCCESS=true
+      #     fi
 
-      - name: Test coverage
-        shell: bash -x -e -u -o pipefail {0}
-        run: |
-          docker exec -t nemo_container_${{ github.run_id }} coverage report -i
+      #     if [[ "$IS_SUCCESS" == "false" ]]; then
+      #       echo Test did not finish successfully.
+      #       exit 1
+      #     fi
 
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        if: ${{ steps.check.outputs.coverage_report != 'none' }}
-        with:
-          name: ${{ steps.check.outputs.coverage_report }}
-          path: |
-            ${{ github.run_id }}/coverage.xml
-            ${{ github.run_id }}/.coverage
-          include-hidden-files: true
+      #     exit $EXIT_CODE
 
-      - uses: "NVIDIA/NeMo/.github/actions/cancel-workflow@main"
-        if: failure() && inputs.IS_OPTIONAL == false && github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'no-fail-fast')
-      - name: after_script
-        if: always() && inputs.AFTER_SCRIPT != ':'
-        run: |
-          docker exec nemo_container_${{ github.run_id }} bash -c '${{ inputs.AFTER_SCRIPT }}'
+      # - name: Test coverage
+      #   shell: bash -x -e -u -o pipefail {0}
+      #   run: |
+      #     docker exec -t nemo_container_${{ github.run_id }} coverage report -i
 
-      - name: Container shutdown
-        if: always()
-        run: |
-          docker container rm -f nemo_container_${{ github.run_id }} || true
+      # - name: Upload artifacts
+      #   uses: actions/upload-artifact@v4
+      #   if: ${{ steps.check.outputs.coverage_report != 'none' }}
+      #   with:
+      #     name: ${{ steps.check.outputs.coverage_report }}
+      #     path: |
+      #       ${{ github.run_id }}/coverage.xml
+      #       ${{ github.run_id }}/.coverage
+      #     include-hidden-files: true
+
+      # - uses: "NVIDIA/NeMo/.github/actions/cancel-workflow@main"
+      #   if: failure() && inputs.IS_OPTIONAL == false && github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'no-fail-fast')
+      # - name: after_script
+      #   if: always() && inputs.AFTER_SCRIPT != ':'
+      #   run: |
+      #     docker exec nemo_container_${{ github.run_id }} bash -c '${{ inputs.AFTER_SCRIPT }}'
+
+      # - name: Container shutdown
+      #   if: always()
+      #   run: |
+      #     docker container rm -f nemo_container_${{ github.run_id }} || true
